export const SEEDED_MEMBERS = [
    { "full_name": "Balkis Zribi", "department_code": "TM_DEPT", "department_label": "TM", "position_code": "MM", "position_label": "MM", "email": "balkis.zribi2005@gmail.com", "phone": "54903021" },
    { "full_name": "Nedim Mejri", "department_code": "TM_DEPT", "department_label": "TM", "position_code": "MM", "position_label": "MM", "email": "najdmejri625@gmail.com", "phone": "29805218" },
    { "full_name": "Iyed Menzli", "department_code": "BD", "department_label": "BD", "position_code": "MM", "position_label": "MM", "email": "iyedmenzli38@gmail.com", "phone": "96690592" },
    { "full_name": "Ines Boujemaa", "department_code": "BD", "department_label": "BD", "position_code": "MM", "position_label": "MM", "email": "ines99.boujemaa@gmail.com", "phone": "27265625" },
    { "full_name": "Melki Siwar", "department_code": "PMEWA", "department_label": "PM&EwA", "position_code": "MM", "position_label": "MM", "email": "siwar.3.melki@gmail.com", "phone": "96781217" },
    { "full_name": "Youssef Koumi", "department_code": "PMEWA", "department_label": "PM&EwA", "position_code": "MM", "position_label": "MM", "email": "youssef.koumi.2025@ihec.ucar.tn", "phone": "26484026" },
    { "full_name": "Ahmed Trigui", "department_code": "MKT", "department_label": "MKT", "position_code": "MM", "position_label": "MM", "email": "ahmed.trigui321@gmail.com", "phone": "98521185" },
    { "full_name": "Azer Nouai", "department_code": "MKT", "department_label": "MKT", "position_code": "MM", "position_label": "MM", "email": "azerkaroui@gmail.com", "phone": "95596696" },
    { "full_name": "Nour Tiouri", "department_code": "MKT", "department_label": "MKT", "position_code": "MM", "position_label": "MM", "email": "nour.tiouiri05@gmail.com", "phone": "28648460" },
    { "full_name": "Adem Allegue", "department_code": "OGV", "department_label": "oGV", "position_code": "TL", "position_label": "TL", "email": "ademalleg10@gmail.com", "phone": "56139985" },
    { "full_name": "Rania Ibn HajKacem", "department_code": "OGV", "department_label": "oGV", "position_code": "TL", "position_label": "TL", "email": "raniahajkacem4@gmail.com", "phone": "58741712" },
    { "full_name": "Eya Shimi", "department_code": "OGV", "department_label": "oGV", "position_code": "TL", "position_label": "TL", "email": "aya2006sh@gmail.com", "phone": "26759421" },
    { "full_name": "Arij Hajji", "department_code": "OGV", "department_label": "oGV", "position_code": "TL", "position_label": "TL", "email": "hajjiarij17@gmail.com", "phone": "53249493" },
    { "full_name": "Rahma Meskini", "department_code": "OGT", "department_label": "oGT", "position_code": "TL", "position_label": "TL", "email": "rahma.elf10@gmail.com", "phone": "29288985" },
    { "full_name": "Nada el ourabi", "department_code": "ICX", "department_label": "ICX", "position_code": "TL", "position_label": "TL", "email": "nadaourabi5@gmail.com", "phone": "53955920" },
    { "full_name": "Yasmine Tlili", "department_code": "ICX", "department_label": "ICX", "position_code": "TL", "position_label": "TL", "email": "yasmine.toto.2005@gmail.com", "phone": "56537478" },
    { "full_name": "Shahd Erokh", "department_code": "ICX", "department_label": "ICX", "position_code": "TL", "position_label": "TL", "email": "chahdouda05@gmail.com", "phone": "29597543" },
    { "full_name": "Ahmed dabbabi", "department_code": "ICX", "department_label": "ICX", "position_code": "TL", "position_label": "TL", "email": "ahmeddabbabi624@gmail.com", "phone": "25041430" },
    { "full_name": "May Ben Farhat", "department_code": "OGV", "department_label": "oGV", "position_code": "TL", "position_label": "TL", "email": "maybenfarhat15@gmail.com", "phone": "56247474" },

    { "full_name": "Omar Boudaya", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "omarboudaya1@gmail.com", "phone": "29762007" },
    { "full_name": "Yosr Arfa", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "arfayosr6@gmail.com", "phone": "94802113" },
    { "full_name": "Aziz Kchaou", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "azizkchaou2005g2@gmail.com", "phone": "" },
    { "full_name": "Nour Dardouri", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "dardourinour24@gmail.com", "phone": "29830898" },
    { "full_name": "Ghofrane Klai", "department_code": "ICX", "department_label": "ICX", "position_code": "TM", "position_label": "TM", "email": "ghofrane.klai07@gmail.com", "phone": "55228996" },
    { "full_name": "Adam Ksantini", "department_code": "MKT", "department_label": "MKT", "position_code": "TM", "position_label": "TM", "email": "ksantini.adem@gmail.com", "phone": "29321808" },
    { "full_name": "Nouha Chiha", "department_code": "ICX", "department_label": "ICX", "position_code": "TM", "position_label": "TM", "email": "nouhachiha76@gmail.com", "phone": "28868838" },
    { "full_name": "Imen Dhieb", "department_code": "BD", "department_label": "BD", "position_code": "TM", "position_label": "TM", "email": "dhiebimene175@gmail.com", "phone": "99395510" },
    { "full_name": "Farah Gretli", "department_code": "ICX", "department_label": "ICX", "position_code": "TM", "position_label": "TM", "email": "farahgritli.10@gmail.com", "phone": "56305379" },
    { "full_name": "Aicha Baccar", "department_code": "ICX", "department_label": "ICX", "position_code": "TM", "position_label": "TM", "email": "abaccaryestunisia2022@gmail.com", "phone": "54562617" },
    { "full_name": "Mayssa Safi", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "mayssagreenshieldhr@gmail.com", "phone": "26878711" },
    { "full_name": "Kenza Ammar", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "ammarkenza5@gmail.com", "phone": "55554840" },
    { "full_name": "Isra Jleli", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "jleliisra75@gmail.com", "phone": "95786993" },
    { "full_name": "Lina Glijou", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "lina.grijou@icloud.com", "phone": "28010522" },
    { "full_name": "Ines Charfi", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "chorfi.in@gmail.com", "phone": "55412941" },
    { "full_name": "Mohamed Fadhel Lassoued", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "mohamedfadhellassoued@gmail.com", "phone": "53688905" },
    { "full_name": "Hamza Belhadj Salah", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "hamzabels85@gmail.com", "phone": "24300449" },
    { "full_name": "Roua Ben Meftah", "department_code": "BD", "department_label": "BD", "position_code": "TM", "position_label": "TM", "email": "rouabenmeftah05@gmail.com", "phone": "29646266" },
    { "full_name": "Othmen Ghozia", "department_code": "MKT", "department_label": "MKT", "position_code": "TM", "position_label": "TM", "email": "ghozia45@gmail.com", "phone": "93858798" },
    { "full_name": "Mohamed Bechir Lazreg", "department_code": "ICX", "department_label": "ICX", "position_code": "TM", "position_label": "TM", "email": "mohamedbechirlazreg@gmail.com", "phone": "26399403" },
    { "full_name": "Hana Feki", "department_code": "BD", "department_label": "BD", "position_code": "TM", "position_label": "TM", "email": "hanafeki8@gmail.com", "phone": "98493000" },
    { "full_name": "Rania Ouerfelli", "department_code": "MKT", "department_label": "MKT", "position_code": "TM", "position_label": "TM", "email": "ouerfellirania96@gmail.com", "phone": "94563094" },
    { "full_name": "Ritej Lassoued", "department_code": "MKT", "department_label": "MKT", "position_code": "TM", "position_label": "TM", "email": "lamia.chouchen@yahoo.fr", "phone": "50977850" },
    { "full_name": "Imen Charef", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "imenec36@gmail.com", "phone": "94271137" },
    { "full_name": "Ranime berriche", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "ranimberrich308@gmail.com", "phone": "95539707" },
    { "full_name": "Amina Chakroun", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "amina.chakroun2006@gmail.com", "phone": "29359339" },
    { "full_name": "mariem ghalia", "department_code": "ICX", "department_label": "ICX", "position_code": "TM", "position_label": "TM", "email": "ghaliyabj@gmail.com", "phone": "" },
    { "full_name": "molka ben aarous", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "molka.benarous.2024@ihec.ucar.tn", "phone": "" },
    { "full_name": "sara toumi", "department_code": "ICX", "department_label": "ICX", "position_code": "TM", "position_label": "TM", "email": "sara.toumi02@gmail.com", "phone": "28854044" },
    { "full_name": "Chahd Mouelhi", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "chahdmouelhi2023@gmail.com", "phone": "24209161" },
    { "full_name": "meriam maaroufi", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "mariewavy2@gmail.com", "phone": "" },
    { "full_name": "chahd briki", "department_code": "ICX", "department_label": "ICX", "position_code": "TM", "position_label": "TM", "email": "chahdbrikiprepa@gmail.com", "phone": "" },
    { "full_name": "Yassine Ajili", "department_code": "ICX", "department_label": "ICX", "position_code": "TM", "position_label": "TM", "email": "yessineajili11@gmail.com", "phone": "44600500" },
    { "full_name": "eya souli", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "eyaasll20@gmail.com", "phone": "" },
    { "full_name": "lina mrad", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "linamrad54@gmail.com", "phone": "53241741" },
    { "full_name": "Farah Jouini", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "juinif41@gmail.com", "phone": "" },
    { "full_name": "Hiba Kourda", "department_code": "ICX", "department_label": "ICX", "position_code": "TM", "position_label": "TM", "email": "kourdahiba1@gmail.com", "phone": "" },
    { "full_name": "Erij Bahri", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "erijhiu3@gmail.com", "phone": "" },
    { "full_name": "houssem eddin zaier", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "daniel.delopi@gmail.com", "phone": "28414428" },
    { "full_name": "mariem hbaieb", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "mariemhbaieb13@gmail.com", "phone": "24266621" },
    { "full_name": "balkis marzouki", "department_code": "ICX", "department_label": "ICX", "position_code": "TM", "position_label": "TM", "email": "mkbalkis0@gmail.com", "phone": "99626898" },
    { "full_name": "may aloui", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "mayaloui444@gmail.com", "phone": "24772538" },
    { "full_name": "nour brahem", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "brahemnour793@gmail.com", "phone": "" },
    { "full_name": "achraf chouchane", "department_code": "OGT", "department_label": "oGT", "position_code": "TM", "position_label": "TM", "email": "achraf.chouchane51@gmail.com", "phone": "" },
    { "full_name": "Dorra beltaarit", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "taaritdorra@gmail.com", "phone": "25469854" },
    { "full_name": "Yasmine Ben Belgacem", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "yasminebenbelgacem15@gmail.com", "phone": "56444014" },
    { "full_name": "kenza mnasri", "department_code": "OGV", "department_label": "oGV", "position_code": "TM", "position_label": "TM", "email": "kenzamnassri85@gmail.com", "phone": "" },
];



